/**
 * setup-fonts.js
 *
 * Copies @fontsource font CSS and woff2 files for Syne and JetBrains Mono into
 * the assets/fonts directory so the API server can serve them locally instead
 * of loading them from the Google Fonts CDN.  This ensures the dashboard
 * renders correctly in offline and air-gapped environments.
 *
 * Usage:
 *   npm install          # runs this script automatically via postinstall
 *   npm run setup-fonts  # or run it explicitly
 *
 * Output:
 *   assets/fonts/fonts.css          – combined @font-face CSS
 *   assets/fonts/files/*.woff2      – latin font files for each weight
 */

'use strict';

const fs   = require('fs');
const path = require('path');

// ---------------------------------------------------------------------------
// Configuration – only the weights actually referenced by the dashboard CSS
// ---------------------------------------------------------------------------

const FONT_CONFIGS = [
  {
    pkg:     '@fontsource/syne',
    family:  'Syne',
    subsets: ['latin'],
    weights: [400, 600, 700, 800],
    style:   'normal',
  },
  {
    pkg:     '@fontsource/jetbrains-mono',
    family:  'JetBrains Mono',
    subsets: ['latin'],
    weights: [300, 400, 500],
    style:   'normal',
  },
];

// ---------------------------------------------------------------------------
// Paths
// ---------------------------------------------------------------------------

const ROOT_DIR      = path.join(__dirname, '..');
const NODE_MODULES  = path.join(ROOT_DIR, 'node_modules');
const ASSETS_FONTS  = path.join(ROOT_DIR, 'assets', 'fonts');
const FONTS_FILES   = path.join(ASSETS_FONTS, 'files');

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

/**
 * Return the URL that will be used in the generated CSS for a given font file.
 * The Rust ServeDir handler exposes fonts under /assets/fonts, so the
 * browser-visible URL is /assets/fonts/files/<filename>.
 */
function fontFileUrl(filename) {
  return `/assets/fonts/files/${filename}`;
}

// ---------------------------------------------------------------------------
// Main
// ---------------------------------------------------------------------------

function main() {
  // Ensure output directories exist
  fs.mkdirSync(FONTS_FILES, { recursive: true });

  const cssParts = [
    '/* Self-hosted fonts generated by scripts/setup-fonts.js                    */',
    '/* DO NOT EDIT MANUALLY – re-run `npm run setup-fonts` to regenerate.       */',
    '',
  ];

  for (const config of FONT_CONFIGS) {
    const pkgDir = path.join(NODE_MODULES, config.pkg);

    if (!fs.existsSync(pkgDir)) {
      console.error(`ERROR: package ${config.pkg} not found in node_modules.`);
      console.error('       Run `npm install` first.');
      process.exit(1);
    }

    for (const subset of config.subsets) {
      for (const weight of config.weights) {
        // e.g. syne-latin-400-normal.woff2
        const woff2Name = `${config.family.toLowerCase().replace(/\s+/g, '-')}-${subset}-${weight}-${config.style}.woff2`;
        const srcWoff2  = path.join(pkgDir, 'files', woff2Name);

        if (!fs.existsSync(srcWoff2)) {
          console.warn(`WARN: ${srcWoff2} not found – skipping`);
          continue;
        }

        // Copy the woff2 file to assets/fonts/files/
        const destWoff2 = path.join(FONTS_FILES, woff2Name);
        fs.copyFileSync(srcWoff2, destWoff2);
        console.log(`Copied ${woff2Name}`);

        // Build a minimal @font-face block for this variant
        const fontFace = [
          `/* ${config.family} – ${subset} ${weight} ${config.style} */`,
          '@font-face {',
          `  font-family: '${config.family}';`,
          `  font-style: ${config.style};`,
          `  font-display: swap;`,
          `  font-weight: ${weight};`,
          `  src: url('${fontFileUrl(woff2Name)}') format('woff2');`,
          '}',
          '',
        ].join('\n');

        cssParts.push(fontFace);
      }
    }
  }

  // Write the combined CSS
  const cssOut = path.join(ASSETS_FONTS, 'fonts.css');
  fs.writeFileSync(cssOut, cssParts.join('\n'), 'utf8');
  console.log(`\nWrote ${cssOut}`);
  console.log('Font setup complete. The API server will now serve fonts locally.');
}

main();
